mutation CreateTransaccion(
  $Tipo: String
  $Numero: String
  $Estado: String
){
	CreateTransaccion(
    Tipo: $Tipo
    Numero: $Numero
    Estado: $Estado
  ){
    Id
    Tipo
    Numero
    Estado
  }
}
