mutation IngresoRemoveItem(
  $IngresoId: Int
  $IngresoItemId: Int
){
  IngresoRemoveItem(
    IngresoId: $IngresoId
    IngresoItemId: $IngresoItemId
  ){
  	Id
    Fecha
    Numero
    PeriodoId
    Concepto
    Total
    Items {
      CuentaDebe {
        Id
        Type
        Code
        Name
      }
      CuentaHaber {
        Id
        Type
        Code
        Name
      }
      Monto
    }
  }
}
