mutation CreateCuenta(
  $Id: Int
  $Type: String
  $Code: String
  $Name: String
){
  UpdateCuenta(
    Id: $Id
    Type: $Type
    Code: $Code
    Name: $Name
  ){
    Id
    Type
    Code
    Name
    Tercero {
      Id
      DianIdentificacion{
        Id
        Codigo
        Nombre
      }
      NumeroDeIdentificacion
      PrimerApellido
      PrimerNombre
      RazonSocial
    }
  }
}
