mutation UpdateTercero (
  $TipoDeIdentificacion: String,
  $NumeroDeIdentificacion: String,
  $DigitoDeVerificacion: String,
  $PrimerApellido: String,
  $SegundoApellido: String,
  $PrimerNombre: String,
  $OtrosNombres: String,
  $RazonSocial: String,
  $Direccion: String,
  $DianPaisId: Int,
  $DianDepartamentoId: Int,
  $DianCiudadId: Int
) {
  UpdateTercero (
    TipoDeIdentificacion: $TipoDeIdentificacion,
    NumeroDeIdentificacion: $NumeroDeIdentificacion,
    DigitoDeVerificacion: $DigitoDeVerificacion,
    PrimerApellido: $PrimerApellido,
    SegundoApellido: $SegundoApellido,
    PrimerNombre: $PrimerNombre,
    OtrosNombres: $OtrosNombres,
    RazonSocial: $RazonSocial,
    Direccion: $Direccion,
    DianPaisId: $DianPaisId
    DianDepartamentoId: $DianDepartamentoId,
    DianCiudadId: $DianCiudadId
  ){
    Id
    TipoDeIdentificacion
    NumeroDeIdentificacion
    DigitoDeVerificacion
    PrimerApellido
    SegundoApellido
    PrimerNombre
    OtrosNombres
    RazonSocial
    Direccion
    DianPaisId
    DianDepartamentoId
    DianCiudadId
  }
}
