mutation UpdateSaldoInicial(
  $Id: Int
  $PeriodoId: Int
  $CuentaId: Int
  $Monto: Float
){
  UpdateSaldoInicial(
    Id: $Id
    PeriodoId: $PeriodoId
    CuentaId: $CuentaId
    Monto: $Monto
  )
  {
    Id
    Periodo {
      Id
      Nombre
      FechaInicial
      FechaFinal
    }
    Cuenta {
      Id
      Code
      Name
      Type
    }
    Monto
  }
}
