INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('91', 'Amazonas');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('05', 'Antioquia');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('81', 'Arauca');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('08', 'Atlántico');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('11', 'Bogotá D.C.');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('13', 'Bolívar');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('15', 'Boyacá');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('17', 'Caldas');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('18', 'Caquetá');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('85', 'Casanare');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('19', 'Cauca');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('20', 'Cesar');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('27', 'Chocó');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('23', 'Córdoba');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('25', 'Cundinamarca');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('94', 'Guainía');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('95', 'Guaviare');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('41', 'Huila');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('44', 'La Guajira');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('47', 'Magdalena');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('50', 'Meta');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('52', 'Nariño');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('54', 'Norte de Santander');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('86', 'Putumayo');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('63', 'Quindío');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('66', 'Risaralda');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('88', 'San Andrés');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('68', 'Santander');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('70', 'Sucre');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('73', 'Tolima');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('76', 'Valle del Cauca');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('97', 'Vaupés');
INSERT INTO "DianDepartamento" ("Codigo", "Nombre") VALUES ('99', 'Vichada');
