CREATE TABLE IF NOT EXISTS "User" (
  "Id" BIGSERIAL PRIMARY KEY,
  "UserName" TEXT UNIQUE,
  "Password" TEXT,
  "Active" TEXT
);

CREATE TABLE IF NOT EXISTS "Group" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Name" TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS "UserGroup" (
  "UserId" BIGINT REFERENCES "User"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "GroupId" BIGINT REFERENCES "Group"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY ("UserId", "GroupId")
);


/*empresa*/
CREATE TABLE IF NOT EXISTS "DianIdentificacion" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Codigo" TEXT UNIQUE,
  "Nombre" TEXT
);


CREATE TABLE IF NOT EXISTS "DianPais" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Codigo" TEXT UNIQUE,
  "Nombre" TEXT
);


CREATE TABLE IF NOT EXISTS "DianDepartamento" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Codigo" TEXT UNIQUE,
  "Nombre" TEXT
);


CREATE TABLE IF NOT EXISTS "DianCiudad" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Codigo" TEXT UNIQUE,
  "Nombre" TEXT
);


CREATE TABLE IF NOT EXISTS "Periodo" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Nombre" TEXT UNIQUE,
  "Estado" TEXT
);


CREATE TABLE IF NOT EXISTS "Tercero" (
  "Id" BIGSERIAL PRIMARY KEY,
  "DianIdentificacionId" BIGINT REFERENCES "DianIdentificacion"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "NumeroDeIdentificacion" TEXT NOT NULL,
  "PrimerApellido" TEXT,
  "SegundoApellido" TEXT,
  "PrimerNombre" TEXT,
  "OtrosNombres" TEXT,
  "RazonSocial" TEXT,
  "Direccion" TEXT,
  "DianPaisId" BIGINT REFERENCES "DianPais"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "DianDepartamentoId" BIGINT REFERENCES "DianDepartamento"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "DianCiudadId" BIGINT REFERENCES "DianDepartamento"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE ("DianIdentificacionId", "NumeroDeIdentificacion")
);


CREATE TABLE IF NOT EXISTS "Cuenta" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Type" TEXT,
  "Code" TEXT,
  "Name" TEXT,
  "TerceroId" BIGINT REFERENCES "Tercero"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE("Type", "Code")
);


CREATE TABLE IF NOT EXISTS "Transaccion" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Tipo" TEXT,
  "Numero" TEXT,
  "Estado" TEXT,
  UNIQUE("Tipo", "Numero")
);


CREATE TABLE IF NOT EXISTS "Ingreso" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Fecha" DATE,
  "Numero" TEXT UNIQUE,
  "PeriodoId" BIGINT REFERENCES "Periodo"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Concepto" TEXT,
  "Total" DECIMAL
);


CREATE TABLE IF NOT EXISTS "IngresoItem" (
  "IngresoId" BIGSERIAL REFERENCES "Ingreso"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaDebeId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaHaberId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Monto" DECIMAL,
  PRIMARY KEY ("IngresoId", "CuentaDebeId", "CuentaHaberId")
);


CREATE TABLE IF NOT EXISTS "Causacion" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Fecha" DATE,
  "Numero" TEXT UNIQUE,
  "PeriodoId" BIGINT REFERENCES "Periodo"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Concepto" TEXT,
  "Total" DECIMAL
);


CREATE TABLE IF NOT EXISTS "CausacionItem" (
  "Id" BIGSERIAL PRIMARY KEY,
  "CausacionId" BIGINT REFERENCES "Causacion"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaDebeId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaHaberId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Monto" DECIMAL,
  "Saldo" DECIMAL
);


CREATE TABLE IF NOT EXISTS "Pago" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Fecha" DATE,
  "Numero" TEXT UNIQUE,
  "PeriodoId" BIGINT REFERENCES "Periodo"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Concepto" TEXT,
  "Total" DECIMAL,
  "TransaccionId" BIGINT REFERENCES "Transaccion"("Id") ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS "PagoItem" (
  "PagoId" BIGINT REFERENCES "Pago"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CausacionItemId" BIGINT REFERENCES "CausacionItem"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaDebeId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Monto" DECIMAL,
  PRIMARY KEY ("PagoId", "CausacionItemId", "CuentaDebeId")
);


CREATE TABLE IF NOT EXISTS "Nota" (
  "Id" BIGSERIAL PRIMARY KEY,
  "Fecha" DATE,
  "Numero" TEXT UNIQUE,
  "PeriodoId" BIGINT REFERENCES "Periodo"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Concepto" TEXT,
  "Total" DECIMAL
);


CREATE TABLE IF NOT EXISTS "NotaItem" (
  "NotaId" BIGSERIAL REFERENCES "Nota"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaDebeId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "CuentaHaberId" BIGINT REFERENCES "Cuenta"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "Monto" DECIMAL,
  PRIMARY KEY ("NotaId", "CuentaDebeId", "CuentaHaberId")
);
